### ISSUE TITLE
What is the role of SN74LVC1G332DBVR

### ISSUE THREAD

**Issue by duoffice** [sillyhatday/GAMEBOY-FLASHCART-MBC5#8]
I know that in MBC1, this chip is compatible with Mario 2 and Mario 3 saves, but MBC5 doesn't seem to need this chip

**Comment by sillyhatday** [comment]
MBC5 does indeed not need this chip most of the time for FRAM. I added it due to request from others who feel better having it there. This is also why I added a bypass for it. You can just solder over the jumper and not use it. Do note that I have found that 4MB MBC5 games do require the CE to be cycled between memory address changes.
